/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listadellaspesa;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Francesco
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    private Utente utente;
    private DefaultListModel listaCarrello;
    private DefaultListModel listaProdottiDispoinibili;
    private float costoOrdine;

    public MainFrame() {
        
        this.listaProdottiDispoinibili = new DefaultListModel();
        this.listaCarrello = new DefaultListModel();

        initComponents();
        setListaProdotti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListProdotti = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListSpesa = new javax.swing.JList<>();
        jButtonAggiungiAlCarrello = new javax.swing.JButton();
        jButtonRimuoviElemento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonSvuotaCarrello = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelOrdini = new javax.swing.JLabel();
        jLabelCostoTotale = new javax.swing.JLabel();
        jButtonOrdina = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNomeUtente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNumeroCarta = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitolo = new javax.swing.JLabel();
        jLabelEsci = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setForeground(new java.awt.Color(255, 204, 51));
        setResizable(false);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setViewportView(jListProdotti);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quantità");

        jListSpesa.setFocusable(false);
        jScrollPane4.setViewportView(jListSpesa);

        jButtonAggiungiAlCarrello.setText("Aggiungi al Carrello");
        jButtonAggiungiAlCarrello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggiungiAlCarrelloActionPerformed(evt);
            }
        });

        jButtonRimuoviElemento.setText("Rimuovi Elemento");
        jButtonRimuoviElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRimuoviElementoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Il tuo carrello");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Prodotti Disponibili");

        jButtonSvuotaCarrello.setText("Svuota Carrello");
        jButtonSvuotaCarrello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSvuotaCarrelloActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelOrdini.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOrdini.setText("Ordini nel carrello: 0");

        jLabelCostoTotale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCostoTotale.setText("Costo totale: 0");

        jButtonOrdina.setText("Ordina Online");
        jButtonOrdina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrdini)
                    .addComponent(jLabelCostoTotale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOrdina, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelOrdini)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelCostoTotale))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonOrdina, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAggiungiAlCarrello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRimuoviElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSvuotaCarrello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel4)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAggiungiAlCarrello)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonRimuoviElemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSvuotaCarrello))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Ordina Online", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Saldo Disponibile:");

        jLabelNomeUtente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelNomeUtente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeUtente.setText("\"nome_utente\"");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Nome Utente: ");

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPassword.setText("\"Passwd\"");

        jLabelSaldo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSaldo.setText("\"saldo\"");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Numero Carta:");

        jLabelNumeroCarta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelNumeroCarta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumeroCarta.setText("\"NumCarta\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelNumeroCarta))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNomeUtente, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelSaldo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeUtente)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelPassword))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelSaldo))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelNumeroCarta))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informazioni Utente", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        jLabelTitolo.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabelTitolo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitolo.setText("Ciao \"username\" cosa vuoi fare?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitolo)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabelEsci.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabelEsci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEsci.setText("Esci dall'account");
        jLabelEsci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEsciMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setText("Cosa vuoi fare?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabelEsciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEsciMouseClicked
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEsciMouseClicked

    private void jButtonRimuoviElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRimuoviElementoActionPerformed
        // TODO add your handling code here:
        String itemSelezionato = jListSpesa.getSelectedValue();
        String[] costoValoreSelezionato = itemSelezionato.split("EUR: ");
        costoOrdine -= Float.valueOf(costoValoreSelezionato[1]);

        int index = jListSpesa.getSelectedIndex();
        listaCarrello.remove(index);
        setTextLabelInfo(costoOrdine);
        jListSpesa.setModel(listaCarrello);
    }//GEN-LAST:event_jButtonRimuoviElementoActionPerformed

    private void jButtonAggiungiAlCarrelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggiungiAlCarrelloActionPerformed
        // TODO add your handling code here:

        int quantita = (int) jSpinner1.getValue();
        String itemSelezionato = jListProdotti.getSelectedValue();
        String[] costoValoreSelezionato = itemSelezionato.split("EUR: ");

        for (int i = 0; i < quantita; i++) {
            listaCarrello.addElement(itemSelezionato);
            costoOrdine += Float.valueOf(costoValoreSelezionato[1]);
        }
        jListSpesa.setModel(listaCarrello);
        setTextLabelInfo(costoOrdine);
        System.out.println(costoOrdine);
    }//GEN-LAST:event_jButtonAggiungiAlCarrelloActionPerformed

    private void jButtonSvuotaCarrelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSvuotaCarrelloActionPerformed
        // TODO add your handling code here:
        listaCarrello.clear();
        costoOrdine = 0;
        setTextLabelInfo(costoOrdine);
    }//GEN-LAST:event_jButtonSvuotaCarrelloActionPerformed

    private void jButtonOrdinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdinaActionPerformed
        // TODO add your handling code here:
        if (utente.getSaldoCarta() >= costoOrdine) {
            String a = JOptionPane.showInputDialog("Dove si dovrà spedire?");
            listaCarrello.clear();
            JOptionPane.showMessageDialog(this, "Ordinazione a " + a + " avvenuta con successo", "Ordine", JOptionPane.PLAIN_MESSAGE);

            utente.setSaldoCarta(utente.getSaldoCarta() - costoOrdine);
            jLabelSaldo.setText(String.valueOf(utente.getSaldoCarta()));

            costoOrdine = 0;
            setTextLabelInfo(costoOrdine);
        } else {
            JOptionPane.showMessageDialog(this, "Saldo non sufficiente per effettuare l'ordine", "Saldo insufficiente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOrdinaActionPerformed

    private void setTextLabelInfo(float prezzo) {
        jLabelCostoTotale.setText("Costo carrello: " + prezzo);
        jLabelOrdini.setText("Numero Ordini: " + listaCarrello.getSize());
    }

    private void setListaProdotti() {
        for (ProdottiEnum x : ProdottiEnum.values()) {
            listaProdottiDispoinibili.addElement(x.info(x));
        }
        jListProdotti.setModel(listaProdottiDispoinibili);
    }

    public void setUtente(Utente p) {
        this.utente = p;
    }

    public JLabel getjLabelNumeroCarta() {
        return jLabelNumeroCarta;
    }

    public JLabel getjLabelPassword() {
        return jLabelPassword;
    }

    public JLabel getjLabelSaldo() {
        return jLabelSaldo;
    }

    public JLabel getjLabelTitolo() {
        return jLabelTitolo;
    }

    public JLabel getjLabelNomeUtente() {
        return jLabelNomeUtente;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAggiungiAlCarrello;
    private javax.swing.JButton jButtonOrdina;
    private javax.swing.JButton jButtonRimuoviElemento;
    private javax.swing.JButton jButtonSvuotaCarrello;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCostoTotale;
    private javax.swing.JLabel jLabelEsci;
    private javax.swing.JLabel jLabelNomeUtente;
    private javax.swing.JLabel jLabelNumeroCarta;
    private javax.swing.JLabel jLabelOrdini;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelTitolo;
    private javax.swing.JList<String> jListProdotti;
    private javax.swing.JList<String> jListSpesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
